// Single source of truth for the legacy ZS script order.
// Refonte progressive : spawn + sentier uniquement (pas de secteurs / RoadNetwork legacy).
export const LEGACY_MODULES = [
  '/js/items.js',
  '/js/survival.js',
  '/js/craft.js',
  '/js/noise.js',
  '/js/camp_textures.js',
  '/js/buildings.js',
  '/js/mapgen.js',
  '/js/campfire.js',
  '/js/decor_colliders.js',
  '/js/trails.js',
  '/js/spawn_clearing.js',
  '/js/proc_spawn.js',
  '/js/world.js',
  '/js/player.js',
  '/js/icons.js',
  '/js/audio.js',
  '/js/zombie.js',
  '/js/rcon.js',
  '/js/chat.js',
  '/js/network.js',
  '/js/ui.js',
  '/js/inventory.js',
  '/js/map.js',
  '/js/game.js',
];
